name: multiEnv

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:

  #first job DEV
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: Checkout the files
      uses: actions/checkout@v1

    - name: Deploy in development environment
      run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r * $HOST_USER@$SERVER_IP:$TARGET
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_DEV}}
      SERVER_IP: ${{secrets.HOST_DNS_DEV}}
      HOST_USER: ${{secrets.USERNAME}}
      TARGET: ${{secrets.TARGET_PATH_DEV}}
  
  #second job PROD
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: DEV
    steps:

    - name: Checkout the files
      uses: actions/checkout@v1

    - name: Deploy in production evnironment
      run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r * $HOST_USER@$SERVER_IP:$TARGET
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_UAT}}
      SERVER_IP: ${{secrets.HOST_DNS_UAT}}
      HOST_USER: ${{secrets.USERNAME}}
      TARGET: ${{secrets.TARGET_PATH_UAT}} 


      CI: false 
