name: multiEnv

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  #first job: scan test with Sonarqube 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        
  #second job: build frontend application
  build_frontend:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout the files
      uses: actions/checkout@v3
    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: npm install dipendeces and build frontend
      run: |
        cd frontend
        npm install
        npm run build
    - name: Upload artifact for deployment job
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: frontend/dist
        
  #third job: deploy MEAN Stack application to DEV environment
  deploy_MeanStack_App:
    runs-on: ubuntu-latest
    needs: build_frontend
    environment: DEV
    steps:
    - name: Checkout the files
      uses: actions/checkout@v1
      
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: Deploy frontend and backend in development environment
      run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r dist $HOST_USER@$SERVER_IP:$TARGET_FRONTEND
          scp -r backend $HOST_USER@$SERVER_IP:$TARGET_BACKEND
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_DEV}}
        SERVER_IP: ${{secrets.HOST_DNS_DEV}}
        HOST_USER: ${{secrets.USERNAME}}
        TARGET_FRONTEND: ${{secrets.TARGET_PATH_F}}
        TARGET_BACKEND: ${{secrets.TARGET_PATH_B}}
        
    - name: Run sshpass commands to Starting the NodeJS Application
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.HOST_DNS_DEV }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        run: |
          cd /var/www/multiEnvMeanStackDeploy/backend
          npm install
          pm2 start server.js
          pm2 restart server.js 
        
  #fourth job: deploy MEAN Stack application to PROD environment
  deploy_to_PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy_MeanStack_App
    steps:

    - name: Checkout the files
      uses: actions/checkout@v1
      
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: Deploy in production evnironment
      run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r dist $HOST_USER@$SERVER_IP:$TARGET_FRONTEND
          scp -r backend $HOST_USER@$SERVER_IP:$TARGET_BACKEND
      env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_UAT}}
          SERVER_IP: ${{secrets.HOST_DNS_UAT}}
          HOST_USER: ${{secrets.USERNAME}}
          TARGET_FRONTEND: ${{secrets.TARGET_PATH_PROD_F}}
          TARGET_BACKEND: ${{secrets.TARGET_PATH_PROD_B}} 
      
    - name: Run sshpass commands to Starting the NodeJS Application
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.HOST_DNS_UAT }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY_UAT }}
        run: |
          cd /var/www/multiEnvMeanStackDeployProd/backend
          npm install
          pm2 start server.js
          pm2 restart server.js 

