name: multiEnv

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:

        
  #second job: deploy MEAN Stack application to DEV environment
  deploy_MeanStack_App:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: Checkout the files
      uses: actions/checkout@v1


    - name: Deploy frontend and backend in development environment
      run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          scp -r dist $HOST_USER@$SERVER_IP:$TARGET_FRONTEND
          scp -r backend $HOST_USER@$SERVER_IP:$TARGET_BACKEND
          

        
    env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_DEV}}
        SERVER_IP: ${{secrets.HOST_DNS_DEV}}
        HOST_USER: ${{secrets.USERNAME}}
        TARGET_FRONTEND: ${{secrets.TARGET_PATH_F}}
        TARGET_BACKEND: ${{secrets.TARGET_PATH_B}}
        
  
  


    
